--- 
title: "R para análise de dados"
author: "Ítalo Cegatta"
site: bookdown::bookdown_site
documentclass: book
---


# Apresentação {-}

Este site reúne os materiais utilizados no curso prático de análise de dados com a linguagem de programação R. O objetivo do curso é fornecer aos participantes as habilidades necessárias para iniciar uma análise utilizando o R de forma prática e rápida sem conhecimento prévio.


## Objetivos {-}

Após concluir este material, os alunos irão:

* Estar familiarizados com o ambiente de programação do R e RStudio
* Seja capaz de visualizar seus dados
* Ser capaz de executar etapas básicas de preparação de dados
* Ser capaz de executar a transformação de dados e resumos
* Ser capaz de calcular estatística básica


## Estrutura {-}

O curso é composto de 3 módulos sequenciais, cada um com uma carga horária de 16 horas. Este material é utilizado durante o curso e todos os códigos e exercícios são executados pelos alunos.


## Requisitos {-}

Para realização dos curso, é necessário um computador com as versões mais recentes dos softwares R e RStudio instalados.

* [Software R](https://cran.r-project.org/bin/windows/base/)
* [Software RStudio](https://www.rstudio.com/products/rstudio/download/#download)
* Pacotes `install.packages(c("tidyverse", "readxl", "broom", "car", "agricolae"))`
* Dados
  * [TUME_134_2016.xlsx](https://github.com/italocegatta/cursoR_gmap/raw/master/input/TUME_134_2016.xlsx)
  * [inv_amazonia.xlsx](https://github.com/italocegatta/cursoR_gmap/raw/master/input/inv_amazonia.xlsx)
  * [onix.xlsx](https://github.com/italocegatta/cursoR_gmap/raw/master/input/onix.xlsx)
  * [filmes_imdb.csv](https://github.com/italocegatta/cursoR_gmap/raw/master/input/filmes_imdb.csv)
  * [progenies.csv](https://github.com/italocegatta/cursoR_gmap/raw/master/input/progenies.csv)
  * [ibge_2015_area_floresta_plan.xlsx](https://github.com/italocegatta/cursoR_gmap/raw/master/input/ibge_2015_area_floresta_plan.xlsx)
  * [base_prouni.xlsx](https://github.com/italocegatta/cursoR_gmap/raw/master/input/base_prouni.xlsx)
  
## Programa {-}


### Módulo I {-}


#### Dia 1 {-}

Introdução à linguagem R e Processamento Básico de dados

* Linguagem R e RStudio
* Conceituações básicas do R e sua área de trabalho
* Pacotes e funções básicas
* Manipulação de dados


#### Dia 2 {-}

Visualização de dados e estatística experimental

* Processamento e análise gráfica de dados
* Regressão linear
* ANOVA
* Teste de Tukey


### Módulo II {-}


#### Dia 1 {-}

Elementos básicos da linguagem R

* Tipos de elementos e objetos
* Indexação
*	Strings, fatores e datas
* Joins


#### Dia 2 {-}

Organização de dados, loops e estatística experimental

*	Tidydata
*	Iteração (loops, purrr)
* Análise exploratória
* Estatística experimental


### Módulo III {-}


#### Dia 1 {-}

Processamento geoespacial e Web scraping

* Raster
* Vetor
*	Mapas
* Web scraping


#### Dia 2 {-}

Criação de pacotes e aplicativos interativos

*	Funções
*	Pacotes
* Shiny

